version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Core linters (enabled by default)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Code quality linters (important)
    - bodyclose
    - goconst
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
    
    # Security linters
    - gosec
    
    # Performance linters  
    - prealloc
    - perfsprint
    
  disable:
    # Disabled for initial setup - can be enabled gradually
    - cyclop
    - dupl
    - funlen
    - gocognit
    - gocyclo
    - maintidx
    - nestif
    - varnamelen
    - wrapcheck
    - lll
    - paralleltest
    - testpackage
    - nlreturn

linters-settings:
  govet:
    # Enable all analyzers
    enable-all: true
    # Disable specific analyzers
    disable:
      - fieldalignment # Too strict for this project
      
  gocritic:
    # Enable multiple checks by tags
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - whyNoLint
      
  revive:
    # Enable default rules
    rules:
      - name: exported
        disabled: false
        
  gosec:
    # Exclude specific rules
    excludes:
      - G104 # Audit errors not checked - too many false positives
      
  misspell:
    # Correct spellings using locale preferences for US or UK
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - bodyclose
        - errcheck
        - gosec
        - unparam
    # Exclude examples directory from some checks
    - path: examples/
      linters:
        - gocritic
        - gosec
        - unused
    # Exclude deprecated CEL API warnings (these are expected until we fully migrate)
    - text: "SA1019.*ref.TypeProvider is deprecated"
      linters:
        - staticcheck
    - text: "SA1019.*ref.FieldType is deprecated"
      linters:
        - staticcheck
  max-issues-per-linter: 0
  max-same-issues: 0
