run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Core linters (essential)
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Code quality linters (important)
    - bodyclose
    - gci
    - gofmt
    - goimports
    - goconst
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
    
    # Security linters
    - gosec
    
    # Performance linters  
    - prealloc
    - perfsprint
    
  disable:
    # Disabled for initial setup - can be enabled gradually
    - cyclop
    - dupl
    - funlen
    - gocognit
    - gocyclo
    - maintidx
    - nestif
    - varnamelen
    - wrapcheck
    - lll
    - paralleltest
    - testpackage
    - nlreturn
    - wsl
    - godot
    - godox
    - goerr113
    - gomnd
    - ireturn
    - nonamedreturns
    - exhaustruct
    - gochecknoglobals
    - depguard
    - gomoddirectives
    - gomodguard

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/spandigital/cel2sql)
  goimports:
    local-prefixes: github.com/spandigital/cel2sql
  govet:
    check-shadowing: true
  misspell:
    locale: US
  revive:
    min-confidence: 0.3
  gosec:
    excludes:
      - G404 # Random number generator not cryptographically secure

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - bodyclose
        - errcheck
        - gosec
        - unparam
    # Exclude examples directory from some checks
    - path: examples/
      linters:
        - gocritic
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
