version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Core linters (enabled by default)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Code quality linters (important)
    - bodyclose
    - goconst
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
    
    # Security linters
    - gosec
    
    # Performance linters  
    - prealloc
    - perfsprint
    
  disable:
    # Disabled for initial setup - can be enabled gradually
    - cyclop
    - dupl
    - funlen
    - gocognit
    - gocyclo
    - maintidx
    - nestif
    - varnamelen
    - wrapcheck
    - lll
    - paralleltest
    - testpackage
    - nlreturn
