name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

permissions:
  contents: read
  security-events: write

jobs:
  govulncheck:
    name: Go Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'  # Use version that matches code requirements
          cache: true
          check-latest: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

  nancy:
    name: Nancy Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true  # Nancy can be flaky, don't fail the whole pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'  # Use version that matches code requirements
          cache: true
          check-latest: true

      - name: WriteGoList
        run: go list -json -deps ./... > go.list

      - name: Nancy
        uses: sonatypecommunity/nancy-github-action@v1.0.3
        with:
          nancyCommand: sleuth --path go.list
